services:
  product_service:
    container_name: product_service_web
    build:
      context: ./products-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product_service_db:5432/product_service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - product_service_db

  product_service_db:
    container_name: product_service_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=product_service
    volumes:
      - product_service_data:/var/lib/postgresql/data

  costumers_service:
    container_name: costumers_service_web
    build:
      context: ./costumers-service
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - DATABASE_NAME=costumers_service
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=costumers_service_db
      - DATABASE_PORT=5432
    depends_on:
      - costumers_service_db
    command: python manage.py runserver 0.0.0.0:8000

  costumers_service_db:
    container_name: costumers_service_postgres
    image: postgres
    ports:
      - 5441:5432
    environment:
      - POSTGRES_DB=costumers_service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - costumers_service_data:/var/lib/postgresql/data

  orders_service:
    container_name: orders_service_web
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    ports:
      - "8011:8000"
    depends_on:
      - orders_service_db
    environment:
      - DATABASE_NAME=orders_service
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=orders_service_db
      - DATABASE_PORT=5432
    command: python manage.py runserver 0.0.0.0:8000


  orders_service_db:
    container_name: orders_service_postgres
    image: postgres
    ports:
      - 5440:5432
    environment:
      - POSTGRES_DB=orders_service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - orders_service_data:/var/lib/postgresql/data

volumes:
  product_service_data: {}
  costumers_service_data: {}
  orders_service_data: {}