services:
  product_service:
    container_name: product_service_web
    build:
      context: ./products-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product_service_db:5432/product_service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - product_service_db

  product_service_db:
    container_name: product_service_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=product_service
    volumes:
      - product_service_data:/var/lib/postgresql/data

  costumers_service:
    container_name: costumers_service_web
    build:
      context: ./costumers-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:

    depends_on:
      - costumers_service_db

  costumers_service_db:
    container_name: costumers_service_postgres
    image: postgres
    ports:
      - 5433:5432
    environment:

    volumes:
      - costumers_service_data:/var/lib/postgresql/data

  orders_service:
    container_name: orders_service_web
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:

    depends_on:
      - orders_service_db

  orders_service_db:
    container_name: orders_service_postgres
    image: postgres
    ports:
      - 5434:5432
    environment:

    volumes:
      - orders_service_data:/var/lib/postgresql/data

volumes:
  product_service_data: {}
  costumers_service_data: {}
  orders_service_data: {}