services:
  product_service:
    container_name: product_service_web
    build:
      context: ./products-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product_service_db:5432/product_service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - product_service_db

  product_service_db:
    container_name: product_service_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=product_service
    volumes:
      - product_service_data:/var/lib/postgresql/data

volumes:
  product_service_data: {}